# Generated by Django 6.0.3 on 2026-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_client_address_project_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bug_images/'),
        ),
    ]
